# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  anon.one:
    site_hosts:
      - canonical: anon.one
        redirects:
          - www.anon.one
      - canonical: jp.anon.one
        redirect:
          - www.jp.anon.one
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:Masayuki-Suzuki/Anonymous.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
